name: dcapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  searchable_dropdown:  
  http: ^0.12.0+4
  progress_indicators: ^0.1.4
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.3+4
  flutter_email_sender: ^2.2.2
  share: ^0.6.3
  dio: ^3.0.9
  path_provider: ^1.6.5
  cached_network_image: ^2.0.0
  zefyr:
  markdown: ^2.1.3
  flutter_html: ^0.11.1
  file_picker: ^1.5.1
  flutter_full_pdf_viewer: ^1.0.6
  shared_preferences:
  progress_dialog: 
  carousel_pro: ^1.0.0
  youtube_player_flutter: ^6.0.3+2
  jitsi_meet: ^0.1.4
  flutter_datetime_picker: ^1.3.5
  email_validator: ^1.0.4
  google_fonts: ^0.3.10
  connectivity: ^0.4.2
  just_audio: ^0.1.4 
  sleek_circular_slider: ^1.1.0
  firebase_messaging: ^6.0.13
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/dom1.jpg
     - assets/dom2.jpg
     - assets/dom3.jpg
     - assets/dom4.jpg
     - assets/domcitylogo2.jpg
     - assets/facebook.png
     - assets/twitter.png
     - assets/instagram.png
     - assets/news.png
     - assets/events.png
     - assets/livestream.png
     - assets/prayer.jpg
     - assets/testimony.png
     - assets/devotionals.png
     - assets/Music.png
     - assets/book.jpg
     - assets/fb.png
     - assets/offering2.jpg
     - assets/donate.png
     - assets/register.png
     - assets/audiomesages2.png
     - assets/DcAirforce.png
     - assets/directory.png
     - assets/boss.jpg
     - assets/campmeeting.jpg
     - assets/radio.png
     - assets/pause.png
     - assets/play.png
     - assets/stop.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
